spring:
  application:
    name:
      StudioPhotografy
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jwt:
    key:
      public: ${spring.jwt.key.public}
      private: ${spring.jwt.key.private}